// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQPJUpHQfzAQOO4B33UZA-EQYBXr_Wj2c',
    appId: '1:305982470488:android:4f82f47d3289556fc90d2d',
    messagingSenderId: '305982470488',
    projectId: 'tourism-app-415b4',
    storageBucket: 'tourism-app-415b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZkLcoLEuhpaZpDiTl2HJ2e-Eqt4Hnfu8',
    appId: '1:305982470488:ios:a7d3f3952a61e5fec90d2d',
    messagingSenderId: '305982470488',
    projectId: 'tourism-app-415b4',
    storageBucket: 'tourism-app-415b4.firebasestorage.app',
    iosBundleId: 'com.example.tourismApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZkLcoLEuhpaZpDiTl2HJ2e-Eqt4Hnfu8',
    appId: '1:305982470488:ios:a7d3f3952a61e5fec90d2d',
    messagingSenderId: '305982470488',
    projectId: 'tourism-app-415b4',
    storageBucket: 'tourism-app-415b4.firebasestorage.app',
    iosBundleId: 'com.example.tourismApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPWBsdKjr6yEWXi6jikLxna-l-bqV1IeQ',
    appId: '1:305982470488:web:b0d0ebebef14bbccc90d2d',
    messagingSenderId: '305982470488',
    projectId: 'tourism-app-415b4',
    authDomain: 'tourism-app-415b4.firebaseapp.com',
    storageBucket: 'tourism-app-415b4.firebasestorage.app',
    measurementId: 'G-ZCKPVW2194',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPWBsdKjr6yEWXi6jikLxna-l-bqV1IeQ',
    appId: '1:305982470488:web:b0d0ebebef14bbccc90d2d',
    messagingSenderId: '305982470488',
    projectId: 'tourism-app-415b4',
    authDomain: 'tourism-app-415b4.firebaseapp.com',
    storageBucket: 'tourism-app-415b4.firebasestorage.app',
    measurementId: 'G-ZCKPVW2194',
  );

}